name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          extensions: mbstring, xml, ctype, json, tokenizer, dom, pdo, pdo_mysql
          coverage: none

      - name: Copy .env file
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"

      - name: Create Laravel Directories
        run: |
          mkdir -p storage/framework/sessions
          mkdir -p storage/framework/views
          mkdir -p storage/framework/cache
          mkdir -p storage/logs
          mkdir -p bootstrap/cache
          
      - name: Install Composer Dependencies
        run: composer install --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: Generate Application Key
        run: sudo php artisan key:generate

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install NPM Dependencies
        run: npm install

      - name: Build Assets
        run: npm run production

      - name: Deploy to Server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 13.60.20.164
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd /var/www/school-grid/
            git pull origin main
            composer install --no-dev --optimize-autoloader
            sudo php artisan migrate --force
            sudo php artisan config:cache
            sudo php artisan route:cache
            sudo php artisan view:cache
            sudo php artisan queue:restart